version: '3.1'
services :
  shopee_test:
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/root/go/src/app/Foreign-Currency-BE-Exercise
    ports:
      - "9000:9000"
    restart: always
